-- Deprecated helper.
--
-- Security hardening is now included directly in supabase/migration.sql:
--   - deterministic policy recreation
--   - TO authenticated policies with ownership checks
--   - WITH CHECK on writes
--   - private user-photos bucket
--   - separate storage SELECT/INSERT/UPDATE/DELETE policies
--   - guarded delete_current_user RPC
--
-- Run supabase/migration.sql as the canonical setup/update script.
