"""Generate src/data/exerciseVideoMap.js (app exercise name -> video id) from exercises/_manifest.json.
python3 marketing/exercise-videos/studio3d/pipeline/build_video_map.py   (run from the repo root)"""
import json, os, re, unicodedata
HERE = os.path.dirname(os.path.abspath(__file__))
m = json.load(open(os.path.join(HERE, '..', 'exercises', '_manifest.json')))
raw = json.load(open(os.path.join(HERE, '..', '..', 'research', 'exercises-raw.json')))
OUT = os.path.join(HERE, '..', '..', '..', '..', 'src', 'data', 'exerciseVideoMap.js')

def norm(s):  # must match normalizeExerciseName() in src/data/exerciseVideos.js
    s = unicodedata.normalize('NFC', s).replace('İ', 'i').replace('I', 'ı').lower()
    s = re.sub(r'[—–]', '-', s)
    return re.sub(r'\s+', ' ', s).strip()

ids = {e['id'] for e in m['exercises']}
ALIASES = { 'push-up variations': 'push_up', 'stomach massage series': 'stomach_massage_round', 'long stretch series': 'long_stretch' }
mp = {}
for e in m['exercises']:
    for n in e['app_names'] + [e['names'].get('tr', ''), e['names'].get('en', '')]:
        if n: mp.setdefault(norm(n), e['id'])
for k, v in ALIASES.items(): mp.setdefault(k, v)
# resolve the remaining app names with the same fallbacks the runtime uses
def strip(n):
    s = re.sub(r'^(→\s*ardından|devre[^-]*-|emom[^-]*-|süperset:|superset:|finisher:)\s*', '', norm(n))
    s = s.split(' + ')[0]
    s = re.sub(r'\s*\([^)]*\)\s*$', '', s)
    s = re.sub(r'\s*(x\d+|\d+\s*(sn|s|dk|tekrar))$', '', s)
    return s.strip()
unresolved = []
for r in raw:
    k = norm(r['name'])
    if k in mp: continue
    s = strip(r['name'])
    if s in mp: mp[k] = mp[s]
    else: unresolved.append(r['name'])
os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, 'w') as f:
    f.write('// Generated by marketing/exercise-videos/studio3d/pipeline/build_video_map.py — do not edit by hand.\n')
    f.write('// Normalized app exercise name -> exercise video id (media.fullbalance.app/<version>/<lang>/<id>.mp4).\n')
    f.write('export const EXERCISE_VIDEO_MAP = ' + json.dumps(dict(sorted(mp.items())), ensure_ascii=False, indent=1) + ';\n')
covered = [r['name'] for r in raw if norm(r['name']) in mp]
print(f'map entries {len(mp)}; app names covered {len(covered)}/{len(raw)}')
print('unresolved:', unresolved)
