window.EXERCISE = {
  id: 'dumbbell_bench_press',
  name: { tr: 'Dumbbell Bench Press', en: 'Dumbbell Bench Press', es: 'Press de banca con mancuernas' },
  category: { tr: 'Göğüs · Kol', en: 'Chest · Arms', es: 'Pecho · Brazos' },
  equipmentLabel: { tr: 'Dambıl · Düz bench', en: 'Dumbbells · Flat bench', es: 'Mancuernas · Banco plano' },
  muscles: ['chest', 'delts', 'triceps'],
  tempo: '2-0-1',
  view: { yaw: 20, pitch: 38, zoom: 1.12 },
  alt: { yaw: 90, pitch: 9, title: { tr: 'Yandan bak', en: 'Side view', es: 'Vista lateral' }, text: { tr: 'Ön kollar dik, dambıllar göğsün yanına iner', en: 'Forearms vertical, bells lower beside the chest', es: 'Antebrazos verticales, mancuernas junto al pecho' } },
  props: [['bench', { at: [-0.4, 0, 0], length: 1.2, height: 0.45 }], ['bench', { at: [-0.4, 0, 0], length: 1.2, height: 0.39 }], ['dumbbell', { grip: 'pronated' }]],
  ctx: { anchorX: ['pelvis'], anchorAt: [0, 0], plant: ['ankleL', 'ankleR'] },
  poses: {
    top: { trunk: -90, hip: -10, knee: 92, neck: 14, abd: 12, ground: [['shoulderR', 0.45], ['pelvis', 0.45]],
      holdL: [0.574, 0.03, 0.21], holdR: [0.574, 0.03, 0.21], elbowPole: [-0.3, -0.4, 1] },
    bottom: { trunk: -90, hip: -10, knee: 92, neck: 14, abd: 12, ground: [['shoulderR', 0.45], ['pelvis', 0.45]],
      holdL: [0.273, -0.081, 0.367], holdR: [0.273, -0.081, 0.367], elbowPole: [-0.18, -0.62, 0.77] },
  },
  rest: 'top',
  rep: [
    { to: 'bottom', dur: 2.0, phase: 0 },
    { to: 'top', dur: 1.0, phase: 1 },
  ],
  setup: { tr: 'Sırt, kalça ve baş benchte, ayaklar yerde. Dambıllar omuzların üstünde, kollar dik.',
    en: 'Back, hips and head on the bench, feet flat. Dumbbells over the shoulders, arms straight.',
    es: 'Espalda, cadera y cabeza en el banco, pies en el suelo. Mancuernas sobre los hombros.' },
  phases: [
    { name: { tr: 'İniş', en: 'Lower', es: 'Baja' }, breath: 'in', arc: ['hipR', 'shoulderR', 'elbowR'],
      text: { tr: 'Dambılları göğsün yanına indir. Dirsekler gövdeye ~60°, ön kollar dik.', en: 'Lower the bells beside the chest. Elbows ~60° from the torso, forearms vertical.', es: 'Baja junto al pecho. Codos a ~60° del torso, antebrazos verticales.' } },
    { name: { tr: 'İtiş', en: 'Press', es: 'Empuja' }, breath: 'out',
      text: { tr: 'Yukarı ve hafif içe it. Dambıllar göğsün üstünde buluşsun, çarpışmasın.', en: 'Press up and slightly in until the bells meet over the chest without clanking.', es: 'Empuja arriba y algo hacia dentro hasta juntarlas sobre el pecho.' } },
  ],
  tempoText: { tr: '2 sn in · 1 sn it', en: '2 s down · 1 s up', es: '2 s abajo · 1 s arriba' },
  mistakes: [
    { title: { tr: 'Dirsekler 90° açılıyor', en: 'Elbows flare to 90°', es: 'Codos abiertos a 90°' },
      fix: { tr: 'Dirsekleri ~60° topla', en: 'Tuck the elbows to ~60°', es: 'Cierra los codos a ~60°' },
      fixText: { tr: 'Omuz önü korunur, göğüs çalışır', en: 'Spares the shoulders, loads the chest', es: 'Cuida los hombros y trabaja el pecho' },
      at: 'bottom', pose: { holdL: [0.28, 0.02, 0.4], holdR: [0.28, 0.02, 0.4], elbowPole: [-0.18, -0.1, 1] }, marks: ['elbowL', 'elbowR'], parts: ['upperR'] },
    { title: { tr: 'Dambıllar dışa kaçıyor', en: 'Bells drift wide', es: 'Mancuernas muy abiertas' },
      fix: { tr: 'Ön kolları dik tut', en: 'Keep forearms vertical', es: 'Antebrazos verticales' },
      fixText: { tr: 'Bilek tam dirseğin üstünde', en: 'Wrist stacked over the elbow', es: 'Muñeca justo sobre el codo' },
      at: 'bottom', pose: { holdL: [0.25, -0.1, 0.48], holdR: [0.25, -0.1, 0.48] }, line: ['elbowR', 'wristR'], parts: ['foreR', 'handR'] },
  ],
  cues: [{ tr: 'Bilekler dirseklerin üstünde', en: 'Wrists over elbows', es: 'Muñecas sobre los codos' }, { tr: 'İnişi kontrol et', en: 'Control the stretch', es: 'Controla la bajada' }, { tr: 'Ayaklar yerde sabit', en: 'Feet planted', es: 'Pies firmes en el suelo' }],
};
