window.EXERCISE = {
  id: 'goblet_squat',
  name: { tr: 'Goblet Squat', en: 'Goblet Squat', es: 'Sentadilla goblet' },
  category: { tr: 'Bacak · Kalça', en: 'Legs · Glutes', es: 'Piernas · Glúteos' },
  equipmentLabel: { tr: 'Dambıl', en: 'Dumbbell', es: 'Mancuerna' },
  muscles: ['quads', 'glutes', 'adductors'],
  tempo: '2-0.5-1',
  view: { yaw: 90, pitch: 5 },
  alt: { yaw: 18, pitch: 7, title: { tr: 'Önden bak', en: 'Front view', es: 'Vista frontal' }, text: { tr: 'Dizler ayak uçlarıyla aynı yöne bakar', en: 'Knees track over the toes', es: 'Rodillas en línea con los pies' } },
  setupView: { yaw: 28, pitch: 12 },
  setupMarks: [{ type: 'span', joints: ['ankleR', 'ankleL'], label: { tr: 'Omuz genişliği', en: 'Shoulder width', es: 'Ancho de hombros' } }],
  props: [['goblet']],
  ctx: { anchorX: ['ankleL', 'ankleR'], plant: ['ankleL', 'ankleR'] },
  poses: {
    start: { abd: 8, hrot: 20, sh: 30, el: 120, shAbd: 10, holdL: [0.2, 0.08, 0.04], holdR: [0.2, 0.08, 0.04], elbowPole: [0.4, -1, -0.3], protract: 0.03, neck: -2 },
    bottom: { trunk: 28, hip: 122, knee: 128, abd: 14, hrot: 22, sh: 40, el: 120, shAbd: 10, holdL: [0.2, 0.08, 0.04], holdR: [0.2, 0.08, 0.04], elbowPole: [0.4, -1, -0.3], protract: 0.03, neck: -16, thoracic: -4 },
  },
  rest: 'start',
  rep: [
    { to: 'bottom', dur: 2.0, phase: 0 },
    { to: 'bottom', dur: 0.5, phase: 1 },
    { to: 'start', dur: 1.0, phase: 2 },
  ],
  setup: { tr: 'Ayaklar omuz genişliğinde, parmak uçları hafif dışa. Dambılı üst başından tut, göğsüne yasla.',
    en: 'Feet shoulder-width, toes slightly out. Hold the dumbbell by the top bell against your chest.',
    es: 'Pies al ancho de hombros, puntas un poco hacia fuera. Sujeta la mancuerna contra el pecho.' },
  phases: [
    { name: { tr: 'İniş', en: 'Lower', es: 'Baja' }, breath: 'in',
      text: { tr: 'Kalçayı geri ve aşağı gönder. Göğüs dik, dirsekler dizlerin içinden geçer.', en: 'Sit hips back and down. Chest tall, elbows pass inside the knees.', es: 'Lleva la cadera atrás y abajo. Pecho arriba, codos por dentro de las rodillas.' } },
    { name: { tr: 'Dipte dur', en: 'Pause', es: 'Pausa' }, breath: 'hold', arc: ['hipR', 'kneeR', 'ankleR'], line: ['heelR', 'ballR'],
      text: { tr: 'Uyluklar yere paralel ya da biraz altında. Topuklar yerde kalır.', en: 'Thighs at or just below parallel. Heels stay down.', es: 'Muslos paralelos o algo más abajo. Talones en el suelo.' } },
    { name: { tr: 'Kalkış', en: 'Drive up', es: 'Sube' }, breath: 'out',
      text: { tr: 'Tüm ayakla yeri it, kalçanı sıkarak tamamen dikleş.', en: 'Push through the whole foot and squeeze your glutes to stand tall.', es: 'Empuja con todo el pie y aprieta glúteos hasta quedar de pie.' } },
  ],
  tempoText: { tr: '2 sn in · 0,5 sn dur · 1 sn kalk', en: '2 s down · 0.5 s pause · 1 s up', es: '2 s abajo · 0,5 s pausa · 1 s arriba' },
  mistakes: [
    { title: { tr: 'Dizler içe çöküyor', en: 'Knees cave in', es: 'Rodillas hacia dentro' },
      fix: { tr: 'Dizleri dışa it', en: 'Push the knees out', es: 'Empuja las rodillas hacia fuera' },
      fixText: { tr: 'Dizler 2. ve 3. parmak hizasında', en: 'Knees over the 2nd–3rd toe', es: 'Rodillas sobre el 2.º y 3.er dedo' },
      at: 'bottom', pose: { abd: 4, hrot: 0 }, view: { yaw: 14, pitch: 7 }, marks: ['kneeL', 'kneeR'], parts: ['thigh', 'shin'] },
    { title: { tr: 'Gövde öne kapanıyor', en: 'Chest drops forward', es: 'El pecho cae' },
      fix: { tr: 'Göğsü dik tut', en: 'Keep the chest tall', es: 'Pecho arriba' },
      fixText: { tr: 'Dambıl göğüste, bakış ileride', en: 'Weight on the chest, eyes forward', es: 'Peso en el pecho, mirada al frente' },
      at: 'bottom', pose: { trunk: 46, thoracic: 12, neck: -4, hip: 126, knee: 112 }, line: ['pelvis', 'neck'], parts: ['chest', 'waist'] },
  ],
  cues: [{ tr: 'Göğüs dik', en: 'Chest tall', es: 'Pecho arriba' }, { tr: 'Dizler ayak uçları yönünde', en: 'Knees over toes', es: 'Rodillas sobre los pies' }, { tr: 'Topuklar yerde', en: 'Heels down', es: 'Talones abajo' }],
};
