window.EXERCISE = {
  id: 'lateral_raise',
  name: { tr: 'Lateral Raise', en: 'Lateral Raise', es: 'Elevación lateral' },
  category: { tr: 'Omuz', en: 'Shoulders', es: 'Hombros' },
  equipmentLabel: { tr: 'Dambıl', en: 'Dumbbells', es: 'Mancuernas' },
  muscles: ['delts', 'upperback'],
  tempo: '1-1-2',
  view: { yaw: 12, pitch: 5 },
  alt: { yaw: 60, pitch: 6, title: { tr: 'Çapraz bak', en: 'Angle view', es: 'Vista en ángulo' }, text: { tr: 'Kollar gövdenin biraz önünde', en: 'Arms slightly in front of the body', es: 'Brazos un poco por delante' } },
  props: [['dumbbell', { grip: 'neutral' }]],
  ctx: { anchorX: ['ankleL', 'ankleR'] },
  poses: {
    start: { abd: 5, hrot: 8, sh: 8, shAbd: 12, el: 14, knee: 6, hip: 4, trunk: 4 },
    top: { abd: 5, hrot: 8, sh: 22, shAbd: 84, el: 16, knee: 6, hip: 4, trunk: 4, shRot: -10 },
  },
  rest: 'start',
  rep: [
    { to: 'top', dur: 1.0, phase: 0 },
    { to: 'top', dur: 1.0, phase: 1 },
    { to: 'start', dur: 2.0, phase: 2 },
  ],
  setup: { tr: 'Ayaklar kalça genişliğinde, dizler hafif bükülü. Dambıllar yanda, avuçlar içe bakar.',
    en: 'Feet hip-width, soft knees. Dumbbells at your sides, palms facing in.',
    es: 'Pies al ancho de cadera, rodillas suaves. Mancuernas a los lados, palmas hacia dentro.' },
  phases: [
    { name: { tr: 'Kaldır', en: 'Raise', es: 'Sube' }, breath: 'out', arc: ['hipR', 'shoulderR', 'elbowR'], trace: 'handR',
      text: { tr: 'Kolları yanlara aç, dirsekler önde gitsin. Omuz hizasında dur.', en: 'Raise the arms out to the sides, elbows leading. Stop at shoulder height.', es: 'Abre los brazos a los lados, codos primero. Para a la altura del hombro.' } },
    { name: { tr: 'Tepede dur', en: 'Hold', es: 'Mantén' }, breath: 'hold', aline: true, line: ['handL', 'shoulderL', 'shoulderR', 'handR'],
      text: { tr: 'Kollar yere paralel, omuzlar aşağıda ve rahat.', en: 'Arms parallel to the floor, shoulders down and relaxed.', es: 'Brazos paralelos al suelo, hombros abajo.' } },
    { name: { tr: 'Kontrollü indir', en: 'Lower slowly', es: 'Baja despacio' }, breath: 'in', trace: 'handR',
      text: { tr: 'İki saniyede, sallamadan başlangıca dön.', en: 'Take two seconds back down, no swinging.', es: 'Dos segundos para bajar, sin balanceo.' } },
  ],
  tempoText: { tr: '1 sn kaldır · 1 sn dur · 2 sn indir', en: '1 s up · 1 s hold · 2 s down', es: '1 s arriba · 1 s pausa · 2 s abajo' },
  mistakes: [
    { title: { tr: 'Omuzlar kulağa kalkıyor', en: 'Shrugging', es: 'Encoger los hombros' },
      fix: { tr: 'Omuzları aşağı indir', en: 'Shoulders down', es: 'Hombros abajo' },
      fixText: { tr: 'Boyun uzun, trapezler rahat', en: 'Long neck, relaxed traps', es: 'Cuello largo, trapecios relajados' },
      at: 'top', pose: { shrug: 0.06, shAbd: 100, neck: -6 }, marks: ['shoulderL', 'shoulderR'], parts: ['upper', 'neck'] },
    { title: { tr: 'Gövdeyle sallanmak', en: 'Swinging the torso', es: 'Balancear el torso' },
      fix: { tr: 'Daha hafif ağırlık seç', en: 'Go lighter', es: 'Usa menos peso' },
      fixText: { tr: 'Gövde sabit, hareket sadece omuzdan', en: 'Still torso, move only at the shoulder', es: 'Torso quieto, mueve solo el hombro' },
      at: 'top', pose: { trunk: -14, lumbar: -10, knee: 14, hip: 2 }, view: { yaw: 55, pitch: 6 }, line: ['pelvis', 'neck'], parts: ['waist', 'chest'] },
  ],
  cues: [{ tr: 'Dirsekler önde', en: 'Lead with the elbows', es: 'Codos primero' }, { tr: 'Omuz hizasında dur', en: 'Stop at shoulder height', es: 'Para a la altura del hombro' }, { tr: 'İnişi yavaşlat', en: 'Slow on the way down', es: 'Baja despacio' }],
};
