window.EXERCISE = {
  id: 'push_up',
  name: { tr: 'Şınav', en: 'Push-Up', es: 'Flexión de brazos' },
  category: { tr: 'Göğüs · Kol', en: 'Chest · Arms', es: 'Pecho · Brazos' },
  equipmentLabel: { tr: 'Vücut ağırlığı', en: 'Bodyweight', es: 'Peso corporal' },
  muscles: ['chest', 'triceps', 'delts', 'core'],
  tempo: '2-0-1',
  view: { yaw: 90, pitch: 7 },
  alt: { yaw: 35, pitch: 18, title: { tr: 'Çapraz bak', en: 'Angle view', es: 'Vista en ángulo' }, text: { tr: 'Dirsekler gövdeye ~45° açıyla', en: 'Elbows ~45° from the torso', es: 'Codos a ~45° del torso' } },
  props: [['mat', { at: [0.45, 0.006, 0], length: 2.0, width: 0.84 }]],
  ctx: { anchorX: ['toeL', 'toeR'], anchorAt: [-0.35, 0], plant: ['handL', 'handR'] },
  poses: {
    top: { trunk: 66, sh: 66, shAbd: 12, el: 0, ankle: -38, abd: 3, neck: -8, ground: [['shoulderR', 0.44], ['toeR', 0]], elbowPole: [-0.3, -1, 0.75] },
    bottom: { trunk: 82, sh: 30, shAbd: 25, el: 95, ankle: -30, abd: 3, neck: -6, ground: [['chest', 0.11], ['toeR', 0]], elbowPole: [-0.3, -1, 0.75] },
  },
  rest: 'top',
  rep: [
    { to: 'bottom', dur: 2.0, phase: 0 },
    { to: 'top', dur: 1.0, phase: 1 },
  ],
  setup: { tr: 'Eller omuzların hemen altında, biraz geniş. Topuktan başa tek bir düz çizgi.',
    en: 'Hands just under the shoulders, slightly wide. One straight line from heels to head.',
    es: 'Manos bajo los hombros, algo abiertas. Una línea recta de talones a cabeza.' },
  setupMarks: [{ type: 'aline', joints: ['ankleR', 'pelvis', 'shoulderR'], color: '#22d38a' }],
  phases: [
    { name: { tr: 'İniş', en: 'Lower', es: 'Baja' }, breath: 'in', arc: ['shoulderR', 'elbowR', 'wristR'], line: ['ankleR', 'pelvis', 'shoulderR'],
      text: { tr: 'Dirsekleri bük, vücudu tek parça halinde göğüs yere yaklaşana kadar indir.', en: 'Bend the elbows and lower as one piece until the chest nearly touches the floor.', es: 'Flexiona los codos y baja en bloque hasta casi tocar el suelo con el pecho.' } },
    { name: { tr: 'İtiş', en: 'Push', es: 'Empuja' }, breath: 'out', line: ['ankleR', 'pelvis', 'shoulderR'],
      text: { tr: 'Yeri kendinden uzağa it, kalça ve omuzlar aynı anda yükselsin.', en: 'Push the floor away; hips and shoulders rise together.', es: 'Empuja el suelo; cadera y hombros suben a la vez.' } },
  ],
  tempoText: { tr: '2 sn in · 1 sn çık', en: '2 s down · 1 s up', es: '2 s abajo · 1 s arriba' },
  mistakes: [
    { title: { tr: 'Kalça çöküyor', en: 'Hips sag', es: 'La cadera se hunde' },
      fix: { tr: 'Karnı ve kalçayı sık', en: 'Brace abs and glutes', es: 'Aprieta abdomen y glúteos' },
      fixText: { tr: 'Omuz, kalça ve ayak bileği aynı çizgide', en: 'Shoulder, hip and ankle in one line', es: 'Hombro, cadera y tobillo alineados' },
      at: 'top', pose: { hip: -22, lumbar: -14, ground: [['shoulderR', 0.44], ['toeR', 0]] }, line: ['ankleR', 'pelvis', 'shoulderR'], parts: ['pelvis', 'waist'] },
    { title: { tr: 'Yarım tekrar, baş önde', en: 'Half rep, head leads', es: 'Media repetición' },
      fix: { tr: 'Göğsü yere yaklaştır', en: 'Chest close to the floor', es: 'Pecho cerca del suelo' },
      fixText: { tr: 'Boyun nötr, bakış ellerin biraz önünde', en: 'Neutral neck, eyes just past the hands', es: 'Cuello neutro, mirada delante de las manos' },
      at: 'bottom', pose: { neck: 40, ground: [['chest', 0.2], ['toeR', 0]] }, marks: ['head'], parts: ['neck', 'face', 'hair'] },
  ],
  cues: [{ tr: 'Vücut tek çizgi', en: 'Body in one line', es: 'Cuerpo en línea' }, { tr: 'Dirsekler ~45°', en: 'Elbows ~45°', es: 'Codos a ~45°' }, { tr: 'Yeri it', en: 'Push the floor away', es: 'Empuja el suelo' }],
};
